@echo off
echo Converting all test files to binary format...

echo Creating reference files for write_matrix tests...
python create_reference_files.py

echo Converting test_1x1.txt...
python .\tools\convert.py .\inputs\test_read_matrix\test_1x1.txt .\inputs\test_read_matrix\test_1x1.bin --to-binary

echo Converting test_2x3.txt...
python .\tools\convert.py .\inputs\test_read_matrix\test_2x3.txt .\inputs\test_read_matrix\test_2x3.bin --to-binary

echo Converting test_3x4.txt...
python .\tools\convert.py .\inputs\test_read_matrix\test_3x4.txt .\inputs\test_read_matrix\test_3x4.bin --to-binary

echo Converting test_negative.txt...
python .\tools\convert.py .\inputs\test_read_matrix\test_negative.txt .\inputs\test_read_matrix\test_negative.bin --to-binary

echo Converting test_zeros.txt...
python .\tools\convert.py .\inputs\test_read_matrix\test_zeros.txt .\inputs\test_read_matrix\test_zeros.bin --to-binary

echo Converting test_max_values.txt...
python .\tools\convert.py .\inputs\test_read_matrix\test_max_values.txt .\inputs\test_read_matrix\test_max_values.bin --to-binary

echo Converting test_single_row.txt...
python .\tools\convert.py .\inputs\test_read_matrix\test_single_row.txt .\inputs\test_read_matrix\test_single_row.bin --to-binary

echo Converting test_single_column.txt...
python .\tools\convert.py .\inputs\test_read_matrix\test_single_column.txt .\inputs\test_read_matrix\test_single_column.bin --to-binary

echo Converting invalid_header.txt...
python .\tools\convert.py .\inputs\test_read_matrix\invalid_header.txt .\inputs\test_read_matrix\invalid_header.bin --to-binary

echo Converting incomplete_data.txt...
python .\tools\convert.py .\inputs\test_read_matrix\incomplete_data.txt .\inputs\test_read_matrix\incomplete_data.bin --to-binary

echo Creating empty file...
echo. > .\inputs\test_read_matrix\empty.bin

echo Creating header-only file...
echo 2 2 | python .\tools\convert.py - .\inputs\test_read_matrix\header_only.bin --to-binary

echo All conversions completed!
pause
